blank_issues_enabled: false
contact_links:
  - name: ❌ Help with Extensions
    url: https://mihon.app/docs/faq/browse/extensions
    about: For extension-related questions/issues
  - name: 🖥️ Mihon FAQ
    url: https://mihon.app/docs/faq/general
    about: Foldchiyomi works like Mihon - its guides and FAQ apply here too
